### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by balaji00710** [caddyserver/examples#70]
Am new to this caddy server i downloaded the caddyserver from the website...
placed the caddy in 

> E:\caddy\caddy.exe

my caddy file for my laravel project

> localhost.dev {
>    root ./public
>    fastcgi / 127.0.0.1:9000 php
>    rewrite {
>        to {path} {path}/ /index.php?{query}
>    }
>    tls self_signed
>    log log/access.log
>	errors log/error.log
> }
and saved this caddy file as **"caddy"** in the project folder

i run command from cmd like this:
> E:\caddy> .\caddy.exe -conf E:\myproject\caddy

but i get an 502 bad gateway error on browser..

**Comment by mholt** [comment]
Thanks for your question @balaji00710 , and I'm thrilled that you're using Caddy! This looks more like a question about how to use Caddy rather than a bug report or feature request. Since this issue tracker is reserved for specific, development-focused discussions, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your question there, and thanks for understanding!
